FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

ENV PORT=8080
ENV DB_TYPE=dynamodb
ENV DB_DYNAMONAME=Notes
ENV AWS_REGION=us-east-1
ENV PYTHONUNBUFFERED=1

EXPOSE 8080

CMD ["python", "main.py"]